### ISSUE TITLE
bug in requirement.txt

### ISSUE THREAD

**Issue by Starryskyswt** [cuteyyt/or-nerf#1]
hello,When I input command: pip install -r requirements.txt,I receive a bug as the picture showed below.
I want to know the meaning of the two-line codes:
# Editable install with no version control (groundingdino==0.1.0)
-e /home/yyt/code/cor-nerf/prior/Grounded-Segment-Anything/GroundingDINO
And are those essential for building the  environment?  
If not,I will delete them to build my environment.
I will be grateful if you could help me figure out my problem. 
![1688039311986](https://github.com/cuteyyt/or-nerf/assets/104331482/b6b79524-ab71-47e2-a8c2-426170be87ec)

**Comment by cuteyyt** [comment]
Thanks for your interest in our project. 

It is safe for you to remove these two lines and other similar bad lines in the _requirement.txt_ file. These two lines are related to the [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO.git) usage, and you can install this package by following their instructions directly. This package is **necessary** for segmentation with the text prompt in our project. 

You may encounter a similar problem with external libraries installed with non-standard 'pip install xxx', like [segment anything](https://github.com/facebookresearch/segment-anything.git) as I export the _requirement.txt_ file with pip freeze directly. I have deleted these problematic lines from the _requirement.txt_ file already, and you can install these packages separately by following their instructions directly.

Hope this can solve your question.

**Comment by Starryskyswt** [comment]
Thank you for your answer,I will try to continue reproducing your code. If I encounter any problems in the future, please excuse me for your assistance
