### ISSUE TITLE
How to use box prompt when using SAM

### ISSUE THREAD

**Issue by Starryskyswt** [cuteyyt/or-nerf#6]
Now I want to use the box prompt to select unwanted objects from the frame of the image to get a mask, and then give it to LAMA to inpaint.  I read  https://github.com/facebookresearch/segment-anything but I don't seem to find a way to use Box,  I would like to implement it in a new dataset now, is it to give the range of box for each image in the json file, as follows
<img width="1244" alt="1699447092205" src="https://github.com/cuteyyt/or-nerf/assets/104331482/0ad71176-51d9-4c62-8b38-eab45946d65e">
The process I'm envisioning now is to use colmap to process the dataset first, (if we don't have a spase folder), and then run the gen_mask_sam_box, the rest of the steps are the same as the first two prompts, but I don't understand how to use box prompts right now, could you give me guidance?

**Comment by cuteyyt** [comment]
If you do not mind, you may contact me on WeChat: cute_yyt
